FROM        phusion/baseimage:0.9.17
MAINTAINER  pitrho

# Set up the environment
#
ENV DEBIAN_FRONTEND noninteractive

# Install mongo
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 \
    && echo "%%MONGO_REPO%%" | tee /etc/apt/sources.list.d/mongodb.list \
    && apt-get update && apt-get install -y \
        pwgen awscli \
        mongodb-org=%%MONGO_VERSION%% \
        mongodb-org-server=%%MONGO_VERSION%% \
        mongodb-org-shell=%%MONGO_VERSION%% \
        mongodb-org-mongos=%%MONGO_VERSION%% \
        mongodb-org-tools=%%MONGO_VERSION%% \
    && update-rc.d -f mongod remove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create database directory
RUN mkdir -p /data/db

# Add all services files
RUN mkdir /etc/service/mongo
COPY run.sh /etc/service/mongo/run
COPY enable_backups.sh /enable_backups.sh
COPY backup.sh /backup.sh

EXPOSE 27017 28017

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]
